"""
Pydantic Models for ICU Drug Titration Environment.

Type-safe data contracts for the OpenEnv-compliant RL environment.
Defines Observation, Action, Reward, and State models.
"""

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


# =============================================================================
# SUB-MODELS
# =============================================================================

class Vitals(BaseModel):
    """Patient vital signs."""
    map: float = Field(..., description="Mean Arterial Pressure (mmHg)")
    hr: float = Field(..., description="Heart Rate (bpm)")
    spo2: float = Field(..., description="Oxygen Saturation (%)")
    rr: float = Field(..., description="Respiratory Rate (breaths/min)")
    temp: float = Field(..., description="Temperature (°C)")


class Labs(BaseModel):
    """Patient laboratory values."""
    glucose: float = Field(..., description="Blood Glucose (mg/dL)")
    creatinine: float = Field(..., description="Serum Creatinine (mg/dL)")
    potassium: float = Field(..., description="Serum Potassium (mEq/L)")
    lactate: float = Field(..., description="Blood Lactate (mmol/L)")


class DrugInfo(BaseModel):
    """Information about an active drug infusion."""
    drug_name: str = Field(..., description="Name of the drug")
    current_dose: float = Field(..., description="Current infusion rate/dose")
    unit: str = Field(..., description="Dose unit")
    step_started: int = Field(..., description="Step when drug was started")


class Alert(BaseModel):
    """Clinical alert generated by the environment."""
    severity: str = Field(..., description="Alert severity: critical, warning, info")
    message: str = Field(..., description="Alert message")
    source: str = Field(..., description="Source of the alert (e.g., interaction, dose, vital)")


# =============================================================================
# ACTION
# =============================================================================

class ActionType(str, Enum):
    """Types of clinical actions the agent can take."""
    ADD_DRUG = "add_drug"
    TITRATE = "titrate"
    REMOVE_DRUG = "remove_drug"
    HOLD = "hold"
    ORDER_LAB = "order_lab"
    FLAG_PHYSICIAN = "flag_physician"


class Action(BaseModel):
    """
    Agent action in the ICU environment.

    Represents a clinical decision made by the AI pharmacist agent.
    """
    action_type: ActionType = Field(..., description="Type of clinical action")
    drug: Optional[str] = Field(None, description="Drug name (required for add/titrate/remove)")
    dose: Optional[float] = Field(None, description="Drug dose (required for add/titrate)")

    class Config:
        json_schema_extra = {
            "examples": [
                {"action_type": "add_drug", "drug": "norepinephrine", "dose": 0.1},
                {"action_type": "titrate", "drug": "norepinephrine", "dose": 0.15},
                {"action_type": "remove_drug", "drug": "norepinephrine"},
                {"action_type": "hold"},
                {"action_type": "order_lab"},
                {"action_type": "flag_physician"},
            ]
        }


# =============================================================================
# OBSERVATION
# =============================================================================

class Observation(BaseModel):
    """
    Environment observation returned after each step.

    Contains current patient state visible to the agent.
    """
    vitals: Vitals = Field(..., description="Current vital signs")
    labs: Labs = Field(..., description="Current lab values")
    active_drugs: List[DrugInfo] = Field(default_factory=list, description="Currently active drug infusions")
    current_step: int = Field(..., description="Current simulation step (hour)")
    max_steps: int = Field(..., description="Maximum steps for this task")
    disease: str = Field(..., description="Disease condition being managed")
    task_id: str = Field(..., description="Current task identifier")
    alerts: List[Alert] = Field(default_factory=list, description="Active clinical alerts")
    vitals_in_range: Dict[str, bool] = Field(
        default_factory=dict,
        description="Whether each vital is currently in safe range"
    )
    labs_in_range: Dict[str, bool] = Field(
        default_factory=dict,
        description="Whether each lab is currently in safe range"
    )


# =============================================================================
# REWARD
# =============================================================================

class Reward(BaseModel):
    """
    Reward signal returned after each step.

    Dense reward with detailed breakdown for learning signal interpretability.
    """
    value: float = Field(..., description="Total reward value for this step")
    breakdown: Dict[str, float] = Field(
        default_factory=dict,
        description="Itemized reward components"
    )


# =============================================================================
# STATE
# =============================================================================

class StepRecord(BaseModel):
    """Record of a single step in the episode."""
    step: int
    action: Action
    observation: Observation
    reward: Reward


class State(BaseModel):
    """
    Full environment state for the current episode.

    Contains complete history and metadata for grading and debugging.
    """
    episode_id: str = Field(..., description="Unique episode identifier")
    session_id: str = Field(..., description="Session identifier for multi-session support")
    task_id: str = Field(..., description="Task being executed")
    disease: str = Field(..., description="Disease profile")
    current_step: int = Field(0, description="Current step number")
    max_steps: int = Field(..., description="Maximum steps for this task")
    done: bool = Field(False, description="Whether the episode has ended")
    done_reason: Optional[str] = Field(None, description="Reason the episode ended")
    total_reward: float = Field(0.0, description="Cumulative reward")
    history: List[StepRecord] = Field(default_factory=list, description="Step-by-step history")
    current_vitals: Optional[Vitals] = Field(None, description="Current vital signs")
    current_labs: Optional[Labs] = Field(None, description="Current lab values")
    active_drugs: List[DrugInfo] = Field(default_factory=list, description="Currently active drugs")


# =============================================================================
# API MODELS
# =============================================================================

class ResetRequest(BaseModel):
    """Request body for resetting the environment."""
    task_id: str = Field("easy", description="Task to run: easy, medium, or hard")
    seed: Optional[int] = Field(None, description="Random seed for reproducibility")


class StepResponse(BaseModel):
    """Response from a step action."""
    observation: Observation
    reward: Reward
    done: bool
    terminated: bool = Field(False, description="True if patient hit critical/death threshold")
    truncated: bool = Field(False, description="True if episode ended by step limit")
    info: Dict = Field(default_factory=dict)


class TaskInfo(BaseModel):
    """Information about an available task."""
    task_id: str
    name: str
    description: str
    disease: str
    horizon: int
    difficulty: str
    allowed_drugs: List[str]


class GradeRequest(BaseModel):
    """Request for grading a trajectory."""
    session_id: str = Field(..., description="Session ID of the episode to grade")


class GradeResponse(BaseModel):
    """Grading result."""
    task_id: str
    score: float = Field(..., ge=0.0, le=1.0)
    breakdown: Dict[str, float] = Field(default_factory=dict)
    total_steps: int
    done_reason: Optional[str] = None


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = "healthy"
    version: str = "1.0.0"
    environment: str = "icu_drug_titration"


class BaselineResponse(BaseModel):
    """Baseline evaluation results."""
    scores: Dict[str, float]
    details: Dict[str, Dict]
